//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC5App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Error
    {
        public int ErrorID { get; set; }
        public System.DateTime OccurredAt { get; set; }
        public string Application { get; set; }
        public string Method { get; set; }
        public string Message { get; set; }
        public string Parameters { get; set; }
        public string Error1 { get; set; }
    }
}
