//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC5App.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MatildaNYEntities : DbContext
    {
        public MatildaNYEntities()
            : base("name=MatildaNYEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Error> Errors { get; set; }
        public virtual DbSet<Hotel> Hotels { get; set; }
        public virtual DbSet<RFID> RFIDs { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<ServerApplicationSetting> ServerApplicationSettings { get; set; }
        public virtual DbSet<Trip> Trips { get; set; }
        public virtual DbSet<UserMeasurement> UserMeasurements { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
