//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC5App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServerApplicationSetting
    {
        public int ID { get; set; }
        public string MinimumAllowableVersion { get; set; }
        public int CurrentAPIVersion { get; set; }
        public string AboutURL { get; set; }
        public string PrivacyURL { get; set; }
        public string TermsURL { get; set; }
        public string SupportURL { get; set; }
    }
}
