//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC5App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trip
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> ArrivalDate { get; set; }
        public Nullable<System.DateTime> DepartureDate { get; set; }
        public string ArrivingBy { get; set; }
        public string RequiredImenities { get; set; }
        public Nullable<System.DateTime> StartedAt { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> EstimatedEnd { get; set; }
    }
}
