//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC5App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMeasurement
    {
        public System.Guid UserMeasurementID { get; set; }
        public System.Guid UserID { get; set; }
        public Nullable<int> Head { get; set; }
        public Nullable<int> Chest { get; set; }
        public Nullable<int> Waist { get; set; }
        public Nullable<int> Hip { get; set; }
        public Nullable<int> Inline { get; set; }
        public Nullable<int> Leg { get; set; }
        public Nullable<int> Feet { get; set; }
    
        public virtual User User { get; set; }
    }
}
